update: downgrade vavr version from 1.0.0-alpha-3 to 0.9.0
An error showed when I was trying to run a package built in jdk:11 and springboot:2.7.2
Error: java.lang.IncompatibleClassChangeError: Method 'io.vavr.control.Option io.vavr.control.Option.none()' must be Methodref constant
To prevent this exception, which has not yet found the actual reason why it occurred besides the exception description mentioned above, downgrade the vavr version from 1.0.0-alpha-3 to 0.9.0 and it will let the application run successfully.

Signed-off-by: 胡鹏 <hup_dev@outlook.com>